sonar.projectKey=Raatbek227_Bekjan
sonar.organization=raatbek227
sonar.sources=frontend,backend
sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/uploads/**,**/*.min.js
sonar.sourceEncoding=UTF-8